name: Sync from repoA

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repoB
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add remote repoA
        run: |
          git remote set-url upstream https://github.com/ashwini-m1488/RepoA.git
          git pull upstream main

      - name: Commit changes (if any)
        run: |
          git add .
          git commit -m "Merge changes from repoA" || echo "No changes to commit"
          
      - name: Push changes to repoB
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rahulrajanpk/RepoA.git

          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
