name: Sync from repoA

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual triggering of the workflow
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repoB
        uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --global user.name "rahulrajanpk"
          git config --global user.email "rahulrajanpk@gmail.com"
      - name: Clone
        run: |        
          git clone https://github.com/rahulrajanpk/RepoA.git
      - name: Add remote repoA of Ash
        run: |
          echo "Adding remote upstream..."
          git remote add upstream https://github.com/ashwini-m1488/RepoA.git || echo "Remote already exists"

      - name: Fetch from upstream
        run: |
          git fetch upstream main 
          ls -la
          
      - name: Checkout from upstream
        run: |
          git checkout HEAD -- File1.txt File2.txt
      - name: Merging
        run: |
          git merge upstream/main --allow-unrelated-histories -X theirs
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rahulrajanpk/RepoA.git
          echo "Pushing changes to origin..."
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
