name: Sync from repoA

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual triggering of the workflow
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repoB
        uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --global user.name "rahulrajanpk"
          git config --global user.email "rahulrajanpk@gmail.com"
        
      - name: List current remotes
        run: |
          echo "Listing current remotes..."
          git remote -v
      - name: Clone the project
        run: |
          echo "Adding remote upstream..."
          git clone https://github.com/rahulrajanpk/RepoA.git

      - name: Add remote repoA of Ash
        run: |
          echo "Adding remote upstream..."
          git remote add upstream https://github.com/ashwini-m1488/RepoA.git || echo "Remote already exists"
          git remote -v  # Verify the remote has been added

      - name: Pull changes from upstream
        run: |
          git pull upstream main --allow-unrelated-histories  # Automatically resolve conflicts by keeping upstream/main's changes
      - name: Status (if any)
        run: |
          git status
      
      - name: Commit changes (if any)
        run: |
          git add .
          git commit -m "Merge changes from upstream $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
      - name: List remotes
        run: git remote -v

      - name: Push changes to repoA for rahul
        run: |
          echo "Setting remote URL for pushing..."
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rahulrajanpk/RepoA.git
          echo "Pushing changes to origin..."
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
