name: Sync from repoA

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repoB
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add remote repoA
        run: |
          git remote add repoA https://github.com/ashwini-m1488/RepoA.git
          git fetch repoA

      - name: Configure Git user
        run: |
          git config user.name "rahulrajanpk"
          git config user.email "rahulrajanpk@gmail.com"

      - name: Pull changes from repoA
        run: |
          git config merge.ours.driver true
          git pull repoA main --strategy-option=theirs || true

      - name: Commit changes (if any)
        run: |
          git add .
          git commit -m "Merge changes from repoA" || echo "No changes to commit"
          
      - name: Push changes to repoB
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
